### ISSUE TITLE
Support for value objects

### ISSUE THREAD

**Issue by sskirby** [nulogy/vorpal#16]
Most of the objects in an aggregate should be value objects. However, Vorpal only supports persisting/materializing entities. We should support value objects. There are 2 different use cases that come to mind:
1. Value objects that are 1-to-1 with an entity.
2. Value objects that are *-to-1 with an entity.

Let's flesh out these use cases and come up with solutions!

**Comment by snasirca** [comment]
@sskirby agreed. We should lean more towards designing Value Objects. I'm interested in this as I've just finished the corresponding chapter in IDDD. I also learned from @diogobnulogy that we can [Serialize Many Value Objects into a Database Column in Postgres](https://til-engineering.nulogy.com/posts/fb8a72f754-serializing-many-value-objects-to-database-columns) which I believe would support point 2 above.

**Comment by sskirby** [comment]
Closing this issue for lack of pain. Happy to re-open when a concrete use-case presents itself.
