### ISSUE TITLE
Documentation for building associations

### ISSUE THREAD

**Issue by PSalmers** [nulogy/vorpal#21]
There is currently no documentation for the effects of the options that one can pass to an association configuration when creating a Vorpal map (https://rubydoc.info/github/nulogy/vorpal/master/Vorpal/Dsl/ConfigBuilder). It would be useful to know what the intended effects of these options are for the purpose of debugging associations and aggregates, and in knowing what sorts of associations and aggregates can be represented.

If I did miss existing documentation of these options somewhere please let me know!

**Comment by sskirby** [comment]
@PSalmers the docs are updated! Let me know if you find the info you need.

**Comment by sskirby** [comment]
@PSalmers going to close this issue. If you still feel your concerns have not been met, please add a comment.
