### ISSUE TITLE
Cloning aggregates

### ISSUE THREAD

**Issue by jayuen** [nulogy/vorpal#3]
Dear Sean:

We'd like to see the ability to be able to clone an entire aggregate with the end goal of saving a copy of the entire aggregate.  Currently we are doing this manually and finding that it is tedious to have to nil out foreign associations in order to make it work outside Vorpal.

Thoughts?
Jason

**Comment by sskirby** [comment]
Dear Jason,

I believe that this functionality lies outside the scope of Vorpal. The cloning of an aggregate is usually a concern of the domain within which your aggregate lies. Might I suggest putting the cloning logic into an instance method or a Factory?

Cheers,
